### PR TITLE
Issue #33 : Add support to PHP8

### LINKED ISSUE #33: Add support to PHP8
Hi, is it possible to add support to PHP8 ? Thanks !

### PR DESCRIPTION
**Pull request by Ciloe**
Closed #33 

Signed-off-by: Jimmy ESCRICH <jescrich@ruedesvignerons.com>

### CODE REVIEW

**Comment by Ciloe** [comment]
@WorksDev I just rebased master to get github action workflow. I forgot anything about tests ?

**Comment by Ciloe** [comment]
@WorksDev your version of PHPunit (v9) is not compatible with the minimum of PHP version (7.3 instead of 7.2)

**Review by usox — APPROVED** [review]

**Comment by WorksDev** [comment]
@Ciloe 
Thanks for your commit, could you please take out the github actions part and use it as a dependency for PHP >= 7.3?

**Review by WorksDev — APPROVED** [review]

**Comment by Ciloe** [comment]
Many thanks, I finished, you can merge, if it's ok (I can't :) )

**Pull request merged**
